### PR TITLE
add media controls

### PR DESCRIPTION
**Pull request by NotAKidoS**
had a wrestling match with visualstudio to not reformat the entire thing when i made any change

i lost

-_-

### CODE REVIEW

**Comment by NotAKidoS** [comment]
The main menu feels too crowded, so I placed it in settings. Still doesnt make sense to me to group settings alongside what the main menu catagorizes as "Actions" and "Shortcuts" but : shrug :.

ChilloutVR_zNxzvEhlkE
ChilloutVR_Yw9qXr14FR

**Comment by dakyneko** [comment]
I would like to propose something here: What about making a mod for that? I would prefer not cluttering the Action menu with everything other menus have and I think there are many other features that could be implemented. Like adjusting volume, selecting a track or something to play directly, maybe showing current title. I think those would really fit into a mod on its own. Easy to share too. Thoughts?

**Comment by dakyneko** [comment]
Did you follow up on the idea? I'll close for now due to inactivity.

**Comment by NotAKidoS** [comment]
Only thing interesting was the volume control. Not sure how selecting a track would work.
I probably won't make a mod for media controls as I personally dislike small tweaks being their own mod. Feels more cluttered and fragile, as well as generally being a pain to maintain alongside the base mod.

**Comment by dakyneko** [comment]
What about adding it to this repository. Meaning it's easier to maintain and it serve as example to others modders. Sounds good to me.

**Pull request closed without merging**
